### ISSUE TITLE
Project 생성

### ISSUE THREAD

**Issue by progh2** [app-and-me/JoinUS#1]
프로젝트 관리를 위해서 Projects 메뉴에서 Project를 생성해주세요~ (액션 옆에 있는 메뉴에서)
기관 관리자 권한 있는 사람만 생성 가능한 것으로 보임...
                                                                     
![image](https://github.com/user-attachments/assets/f08df12c-e0b2-42e3-b115-8c7742cc3d98)

**Comment by dayul** [comment]
생성했습니다!
